testsExecutable: tests.o hierarchy.o command.o catch2.o

	g++ -o testsExecutable tests.o hierarchy.o command.o catch2.o

consoleAppExecutable: main.o hierarchy.o command.o

	g++ -o consoleAppExecutable main.o hierarchy.o command.o

tests.o: tests.cpp

	g++ -c tests.cpp	

main.o: main.cpp

	g++ -c main.cpp

hierarchy.o: hierarchy.cpp

	g++ -c hierarchy.cpp

command.o: command.cpp

	g++ -c command.cpp

catch2.o: catch2.cpp

	g++ -c catch2.cpp




	


